export const seedData = {
  users: {
    _model: "User",
    homer: {
      firstName: "Homer",
      lastName: "Simpson",
      email: "homer@simpson.com",
      password: "secret",
    },
    marge: {
      firstName: "Marge",
      lastName: "Simpson",
      email: "marge@simpson.com",
      password: "secret",
    },
    bart: {
      firstName: "Bart",
      lastName: "Simpson",
      email: "bart@simpson.com",
      password: "secret",
    },
    1: {
      firstName: "1",
      lastName: "1",
      email: "1@1.com",
      password: "1",
      privilege: "ADMIN",
    },
  },
  placemarks: {
    _model: "Placemark",
    Kildare: {
      title: "Kildare",
      userid: "->users.1",
    },
  },
  stations: {
    _model: "Station",
    station_1: {
      title: "Texaco",
      lat: 53.4234,
      lng: 7.2022,
      category: "station only",
      description: "Billing",
      unleaded_price: 2.3,
      diesel_price: 1.35,
      placemarkid: "->placemarks.Kildare",
    },
    station_2: {
      title: "Maxoil",
      lat: 52.1234,
      lng: 7.2922,
      category: "station only",
      description: "95 super",
      unleaded_price: 1.2,
      diesel_price: 1.15,
      placemarkid: "->placemarks.Kildare",
    },
    station_3: {
      title: "Shell",
      lat: 51.1214,
      lng: 8.2322,
      category: "station only",
      description: "97 extra",
      unleaded_price: 2.4,
      diesel_price: 1.29,
      placemarkid: "->placemarks.Kildare",
    },
    station_4: {
      title: "Shell",
      lat: 53.1215,
      lng: 7.2122,
      category: "super station",
      description: "95 petrol",
      unleaded_price: 2.4,
      diesel_price: 1.29,
      placemarkid: "->placemarks.Kilkenny",
    },
  },
  messages: {
    _model: "Message",
    message_1: {
      messageText: "test message from a community user",
    },
  },
};
